name: Update email templates

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  update-templates:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
          scope: '@significa'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: npm ci

      - name: Update email templates
        env:
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
        run: ./scripts/update-email-templates.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ci/update-email-templates
          commit-message: 'ci: updated email templates'
          delete-branch: true
          title: 'CI: auto updated email templates'
          body: |
            Updated email templates from Mailchimp.

            Before merging, please make sure that the plaintext versions of the emails
            still make sense.
